version: '3.8'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    env_file:
      - ./.env
    volumes:
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

