version: '3.9'
services:
  mongo:
    image: mongo
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: beneflex-svc
    #   MONGO_INITDB_ROOT_PASSWORD: b3n3@fl3x
    ports:
      - "27017:27017"
    env_file:
      - ./.env
